---
title: Yarn
timezone: UTC
collections:
  my_collection:
    title: My Collection
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Fast, reliable, and secure dependency management.

'
baseurl: ''
url: https://yarnpkg.com
twitter_username: yarnpkg
github_username: yarnpkg
latest_version: 0.19.1
latest_rc_version: 0.19.0
show_rc: false
gacode: UA-85522875-1
exclude:
- README.md
- crowdin.yaml
- Gemfile
- Gemfile.lock
- Makefile
- _sass/bootstrap
- ".sass-cache"
include:
- _redirects
- install.sh
gems:
- jekyll-redirect-from
- jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: rougeHighlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
sass:
  style: compressed
redcarpet:
  extensions:
  - with_toc_data
permalink: "/blog/:year/:month/:day/:title"
paginate: 1
__empty_array__: []
